#!/usr/bin/env python3
"""Regenerates 00_Cerebrum/_ACTION-ITEMS.md from the per-KB Action items tables.

The roll-up is derived, never authored. State lives in each knowledge base's
Wiki/questions.md; this script reads those tables and writes the vault-level
view with the real write time. Never edit _ACTION-ITEMS.md by hand, and never
hand-write its timestamp: on 09.08.2026 a hand-written stamp differed from the
actual write time by 24 minutes, in the one field whose job is staleness.

Usage:  python3 _scripts/actionitems.py
"""
import datetime
import os
import re
import sys

VAULT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Cells may not span lines. Without the \n exclusion the five-cell pattern
# runs past the end of a short row and swallows the next one, which is how
# the two-column 'Deferred' sub-table under this heading got parsed as an
# action item on 15.08.2026 and raised 'unrecognised state AI-2026-08-15-5'.
ROW = re.compile(r'^\|\s*(AI-[^|\n]+)\|([^|\n]*)\|([^|\n]*)\|([^|\n]*)\|([^|\n]*)\|', re.M)


def discover():
    return sorted(d for d in os.listdir(VAULT)
                  if os.path.isdir(os.path.join(VAULT, d, 'Wiki'))
                  and os.path.exists(os.path.join(VAULT, d, 'CLAUDE.md')))


VALID = ('open', 'actioned', 'deferred', 'withdrawn')


def state_of(cell):
    """First word of the state cell, normalised.

    The cell is written by hand and picks up decoration: bold markers,
    strikethrough, a trailing comma before a qualifier ("**open**, narrowed
    09.08.2026"), a date after the state. Take the first word, drop
    surrounding punctuation, lowercase it. An unrecognised value raises
    rather than being counted as nothing, because a silently uncounted open
    item is exactly the failure this roll-up exists to prevent.
    """
    raw = re.sub(r'[*~]', '', cell or '').strip()
    if not raw:
        return '?'
    word = raw.split()[0].strip(' ,.;:()[]').lower()
    if word not in VALID:
        raise ValueError('unrecognised action item state %r in cell %r; '
                         'expected one of %s' % (word, cell, ', '.join(VALID)))
    return word


def items(kb):
    p = os.path.join(VAULT, kb, 'Wiki', 'questions.md')
    if not os.path.exists(p):
        return []
    t = open(p, encoding='utf-8').read()
    m = re.search(r'^# Action items(.*?)^# ', t, re.S | re.M)
    sec = m.group(1) if m else ''
    # Cells are copied verbatim into a file that sits one level up, at the
    # vault root, so a link written relative to <KB>/Wiki/ does not resolve
    # there. Rebase them. Found 15.08.2026: two links to systems/intune.md
    # were the only broken paths left in the vault after the three-way split,
    # and they were in this generated file rather than in any concept.
    def rebase(cell):
        return re.sub(r'\]\((?!https?:|mailto:|#|/)([^)]+\.md)\)',
                      lambda m: '](%s/Wiki/%s)' % (kb, m.group(1)), cell)

    out = []
    for r in ROW.findall(sec):
        out.append(dict(id=r[0].strip(), item=rebase(r[2].strip()),
                        state=state_of(r[3]),
                        res=rebase(r[4].strip())))
    return out


def main():
    kbs = discover()
    data = {kb: items(kb) for kb in kbs}
    c = lambda kb, s: sum(1 for r in data[kb] if r['state'] == s)
    stamp = datetime.datetime.utcnow().strftime('%d.%m.%Y, %H:%M UTC')

    b = ["# Action items across the vault\n",
         "**Generated, not authored. Do not edit this file.** Every item's "
         "state lives in its own knowledge base, in `<KB>/Wiki/questions.md` "
         "under *Action items*. This is a read-only roll-up of the ones still "
         "needing you, written by `_scripts/actionitems.py` at the end of "
         "every run that touches an item.\n",
         "Editing here would create a second place recording the same state, "
         "and the two would drift. Change an item where it lives; this file "
         "catches up on the next run.\n",
         "Last generated **%s**, by script, from the tables themselves. "
         "Knowledge bases covered: %s.\n"
         % (stamp, ', '.join('`%s`' % k for k in kbs)),
         "## Needing you now\n"]

    opens = [(kb, r) for kb in kbs for r in data[kb] if r['state'] == 'open']
    if opens:
        b.append("| Id | Knowledge base | Item | Why it needs judgement |\n"
                 "|---|---|---|---|")
        for kb, r in sorted(opens, key=lambda x: x[1]['id']):
            b.append("| %s | %s | %s | %s |" % (r['id'], kb, r['item'],
                                                r['res']))
        b.append("")
    else:
        b.append("**Nothing.** Every raised item has been actioned or "
                 "withdrawn.\n")

    b.append("## Waiting on a condition\n")
    defs = [(kb, r) for kb in kbs for r in data[kb]
            if r['state'] == 'deferred']
    if defs:
        b.append("| Id | Knowledge base | Item | Reopens when |\n"
                 "|---|---|---|---|")
        for kb, r in sorted(defs, key=lambda x: x[1]['id']):
            b.append("| %s | %s | %s | %s |" % (r['id'], kb, r['item'],
                                                r['res']))
        b.append("")
    else:
        b.append("None.\n")

    b += ["## Closed, counted only\n",
          "Resolved items stay in their own knowledge base with their "
          "reasoning. They are not copied here; a roll-up of everything ever "
          "decided is an archive, not a queue.\n",
          "| Knowledge base | Open | Deferred | Actioned | Withdrawn | "
          "Total raised |\n|---|---|---|---|---|---|"]
    for kb in kbs:
        b.append("| %s | %d | %d | %d | %d | %d |"
                 % (kb, c(kb, 'open'), c(kb, 'deferred'), c(kb, 'actioned'),
                    c(kb, 'withdrawn'), len(data[kb])))
    b += ["",
          "**The withdrawn count is the one to watch.** It records what the "
          "audit got wrong rather than what the corpus got wrong. A rising "
          "withdrawn count means a check needs fixing, not that the vault is "
          "degrading.\n",
          "## Where to act\n"]
    for kb in kbs:
        b.append("- `%s/Wiki/questions.md` — *Action items*, then the section "
                 "each item points at" % kb)
    b.append("\nSay \"ask me the action items\" to be walked through the open "
             "ones one at a time.")

    out = os.path.join(VAULT, '_ACTION-ITEMS.md')
    open(out, 'w', encoding='utf-8').write('\n'.join(b) + '\n')
    print('regenerated %s | open %d, deferred %d'
          % (out, len(opens), len(defs)))


if __name__ == '__main__':
    main()
