#!/usr/bin/env python3
"""Roll up every '# Pending attachments' table in a bundle into one register.

Generated, not authored. State lives in the concepts; this is a read-only view
of it, exactly like _ACTION-ITEMS.md. Run it again after any pass that adds or
clears a Pending attachments row.

Usage: python3 _scripts/attachment-register.py <KB>

It took a notebook directory and a snapshot prefix until 22.08.2026, and read
`<prefix>.missing-images.tsv` to count dropped-image markers. That input no
longer describes anything: the only such snapshot measures the Alpha export of
11.04.2026, deleted on 21.08.2026, and the export that replaced it carries no
dropped-image markers at all. Pointing the script at the surviving file would
have produced a confident register of an archive that is gone, which is worse
than no register — a missing file is visibly missing, and a generated one is
read as measurement.

So the marker arithmetic is gone and the roll-up stays, which is what the
vault manual described the script as doing all along.
"""
import os, re, sys, datetime

import bundle
from tableorder import SEP

kb = sys.argv[1]
vault = bundle.VAULT
wiki = os.path.join(vault, kb, "Wiki")

rows = []
# The bundle's own concept walk, which leaves `_to_delete/` out. This script
# walked the tree for itself until 04.10.2026 and skipped every `_`-prefixed
# directory. Without that the register listed 42 concepts and 75 rows, of
# which 37 concepts were retired copies sitting in
# `_to_delete/2026-08-15-pre-archive-replacement/` — a queue of work against
# concepts that no longer exist. The rows are sorted before they are written,
# so the order of the walk never showed.
for p in bundle.concept_files(kb):
    t = open(p, encoding="utf-8").read()
    m = re.search(r"^# Pending attachments(.*?)(?=^# |\Z)", t, re.S | re.M)
    if not m:
        continue
    rel = os.path.relpath(p, wiki)
    body = [l for l in m.group(1).split("\n")
            if l.startswith("|") and not SEP.match(l)]
    for l in body[1:]:                       # drop the header row
        cells = [re.sub(r"\[\^[^\]]+\]", "", c).strip()
                 for c in l.strip().strip("|").split("|")]
        while len(cells) < 3:
            cells.append("")
        rows.append((rel, cells[0], cells[1], cells[2]))

out = [
 "# Attachment pass register",
 "",
 "**Generated, not authored. Do not edit this file.** Every row's state lives in the "
 "concept that raised it, in a `# Pending attachments` table. This is a read-only "
 "roll-up written by `_scripts/attachment-register.py`. Clear a row where it lives; "
 "this file catches up on the next run.",
 "",
 f"Last generated **{datetime.datetime.now(datetime.timezone.utc).strftime('%d.%m.%Y, %H:%M UTC')}**, "
 f"by script, from the tables themselves.",
 "",
 "## Where the queue stands",
 "",
 "| | |",
 "|---|---|",
 f"| Concepts blocked on an attachment | {len({r[0] for r in rows})} |",
 f"| Rows in this register | {len(rows)} |",
 "",
 "The archive's own size and attachment count are not restated here. They are "
 "measured in `COVERAGE.md` and recorded in `memory.md`.",
 "",
 "## What is blocked",
 "",
 "| Concept | Archive page | Image | Should settle |",
 "|---|---|---|---|",
]
for rel, page, img, what in sorted(rows):
    out.append(f"| [{rel}](Wiki/{rel}) | {page} | {img} | {what} |")

out += [
 "",
 "## Clearing a row",
 "",
 "A row leaves this register when the `# Pending attachments` table that raised it "
 "loses the row, in the concept itself. Open the archive page named beside it, read "
 "the attachment, write what it settles into the concept body with a footnote, and "
 "delete the row. Then re-run this script and `_scripts/verify.py`.",
 "",
 "A concept whose table empties should lose the heading and the `attachments-pending` "
 "tag together. A heading left above an empty table is why compile agents were told "
 "to reroute appends away from these concepts.",
 "",
]
open(os.path.join(vault, kb, "_ATTACHMENT-PASS.md"), "w", encoding="utf-8").write("\n".join(out))
print(len(rows), "rows,", len({r[0] for r in rows}), "concepts")
