#!/usr/bin/env python3
"""Regenerate <KB>/_extractions/_INVENTORY.md — the concept list compile agents read.

A compile agent is told not to explore the tree: an `ls` sweep of a bundle
costs more than the batch it is about to read, and the agent still ends up
with a partial picture. It reads this file instead, once, and that is the
only thing standing between it and writing a concept that already exists
under a slightly different name.

Which makes a stale inventory the expensive failure. On 15.08.2026 it was
four concepts behind — missing exactly what the previous batch had created,
because nothing regenerated it and the step lived only in prose. It had no
generator at all until this file. Prose that says "regenerate the inventory"
is a step someone skips; a script is a step someone runs.

Run it before every dispatch, after the previous wave has merged.

Usage:  python3 _scripts/inventory.py <KB> [more KBs...]
        python3 _scripts/inventory.py --all
        python3 _scripts/inventory.py <KB> --check    (exit 1 if stale)
"""
import glob
import os
import re
import sys

VAULT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FM = re.compile(r'^---\n(.*?)\n---\n', re.S)
RESERVED = ('index.md', 'log.md')
# A description is one line in a table cell. Long ones are cut rather than
# wrapped: the agent needs to recognise the concept, not read it.
DESC_MAX = 140

HEADER = """# Existing concepts — %s

Generated by `_scripts/inventory.py`. Do not edit; regenerate.

Written for compile agents so they need not explore the tree. Path is relative
to the knowledge base root; cite and link by path. **If a concept below already
covers what a page says, extend it with an APPEND block — do not write a second
concept under another name.**

| Concept | Type | Description |
|---|---|---|
"""


def field(fm, key):
    m = re.search(r'^%s:\s*(.+)$' % key, fm, re.M)
    return m.group(1).strip().strip('"\'') if m else ''


def build(kb):
    root = os.path.join(VAULT, kb)
    rows = []
    for f in sorted(glob.glob(os.path.join(root, 'Wiki', '**', '*.md'),
                              recursive=True)):
        if os.path.basename(f) in RESERVED or '_to_delete' in f:
            continue
        m = FM.match(open(f, encoding='utf-8').read())
        if not m:
            continue
        rel = os.path.relpath(f, root).replace(os.sep, '/')
        desc = field(m.group(1), 'description').replace('|', '\\|')
        if len(desc) > DESC_MAX:
            desc = desc[:DESC_MAX].rstrip() + '…'
        rows.append('| `%s` | %s | %s |' % (rel, field(m.group(1), 'type'), desc))
    return (HEADER % kb) + '\n'.join(rows) + '\n', len(rows)


def discover():
    return sorted(d for d in os.listdir(VAULT)
                  if os.path.isdir(os.path.join(VAULT, d, 'Wiki'))
                  and os.path.exists(os.path.join(VAULT, d, 'CLAUDE.md')))


def main():
    check = '--check' in sys.argv
    kbs = [a for a in sys.argv[1:] if not a.startswith('--')]
    if not kbs or '--all' in sys.argv:
        kbs = discover()
    stale = 0
    for kb in kbs:
        ex = os.path.join(VAULT, kb, '_extractions')
        if not os.path.isdir(ex):
            continue  # no compile pipeline in this knowledge base
        out = os.path.join(ex, '_INVENTORY.md')
        text, n = build(kb)
        have = open(out, encoding='utf-8').read() if os.path.exists(out) else ''
        if check:
            if have != text:
                stale += 1
                print('%-12s STALE  (%d concepts on disk)' % (kb, n))
            else:
                print('%-12s ok     (%d concepts)' % (kb, n))
            continue
        open(out, 'w', encoding='utf-8').write(text)
        print('%-12s %3d concepts  %s%s'
              % (kb, n, os.path.relpath(out, VAULT),
                 '' if have == text else '   (was stale)'))
    sys.exit(1 if stale else 0)


if __name__ == '__main__':
    main()
