#!/usr/bin/env python3
"""Turn every Mermaid block in a markdown file into a verifiable URL.

A diagram that has never been rendered is an unverified claim, the same as a
figure nobody checked. On 18.08.2026 three diagrams shipped in a question
report with the honest caveat that they could not be rendered: npm is 403 in
both the session container and the device VM, and cdnjs and jsdelivr are
tunnel-blocked from the container, so no local renderer was reachable.

The way through is the owner's own browser, which has ordinary internet. The
Mermaid live editor encodes the whole diagram in the URL fragment as
zlib-deflated, URL-safe base64 of a small JSON payload. So a URL can be built
here, opened there, and the render either succeeds or shows a parse error.
Driving it with the Claude in Chrome tools makes it a screenshot the
librarian can read, which is what verification means in this vault.

All three diagrams of 18.08.2026 were confirmed this way against Mermaid
v11.16.1 after the URLs were generated by this method.

Usage:  python3 _scripts/mermaid-check.py <markdown file>
        python3 _scripts/mermaid-check.py <file> --json   (for tooling)
"""
import base64
import json
import re
import sys
import zlib

BLOCK = re.compile(r'```mermaid\n(.*?)```', re.S)


def urls_for(path):
    text = open(path, encoding='utf-8').read()
    out = []
    for block in BLOCK.findall(text):
        payload = {'code': block.strip(),
                   'mermaid': json.dumps({'theme': 'dark'}),
                   'autoSync': True,
                   'updateDiagram': True}
        packed = zlib.compress(json.dumps(payload).encode(), 9)
        frag = base64.urlsafe_b64encode(packed).decode().rstrip('=')
        out.append('https://mermaid.live/edit#pako:' + frag)
    return out


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__.strip().split('\n\n')[-1])
    path = sys.argv[1]
    urls = urls_for(path)
    if '--json' in sys.argv:
        print(json.dumps(urls))
        return
    if not urls:
        print('no mermaid blocks in %s' % path)
        return
    print('%d diagram(s) in %s\n' % (len(urls), path))
    for i, u in enumerate(urls, 1):
        print('Diagram %d:\n%s\n' % (i, u))
    print('Open each in a browser with internet access — the Claude in Chrome\n'
          'tools can do it — and screenshot the result. A parse error renders\n'
          'as an error panel rather than a diagram, so the check is visual and\n'
          'cannot be faked by the URL building successfully.')


if __name__ == '__main__':
    main()
