#!/usr/bin/env python3
"""Cuts the unconfirmed concepts into blocks of 50 for the owner to read.

Written 22.08.2026, when the owner answered the read-rule question with "I
want to read everything. Give me a short summary of the concepts (1-3
sentences) and pass me the concepts in blocks of 50."

That answer reframes the problem. `readset.py` derives what a *session* must
read and had started returning whole bundles — 352 concepts and 3.5 MB in
Alpha_kb — which no session reads, so runs were stating a shortfall instead of
meeting the rule. The owner's answer moves the reading to the person who can
actually do it, over as many sittings as it takes, and turns an unmeetable
rule into a queue with a position in it.

A block is 50 concepts, ordered by inbound links within each knowledge base,
highest first. That ordering was wrong once and is kept anyway: on 15.08.2026
the Gamma sitting was ordered the same way on the reasoning that a wrong
claim propagates furthest from a concept the bundle leans on, and the tail —
the concepts nothing links to — returned more findings than the first three
blocks together, because it held most of the Decision concepts and a Decision
carries its own counterfactual. Inbound links measure propagation risk, which
is real. They do not measure where the findings are. Read the tail.

Concepts already carrying a `verified` key are skipped, which is what makes
this resumable: confirm a block, and the next run of this script starts after
it.

Usage:  python3 _scripts/readblocks.py [KB ...]   (default: every KB)
        python3 _scripts/readblocks.py --block 3  (print one block)
        python3 _scripts/readblocks.py --write    (write Outputs/_READING-BLOCKS.md)
"""
import collections
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import verify  # noqa: E402

try:
    import yaml
except ImportError:
    sys.exit('readblocks.py needs PyYAML')

VAULT = verify.VAULT
LINK = re.compile(r'\]\((?!http)([^)]+\.md)\)')
SIZE = 50


def bundle(kb):
    root = os.path.join(VAULT, kb)
    rels, meta = [], {}
    for p in sorted(glob.glob(os.path.join(root, 'Wiki', '**', '*.md'),
                              recursive=True)):
        if os.path.basename(p) in ('index.md', 'log.md') or '_to_delete' in p:
            continue
        rel = os.path.relpath(p, root).replace(os.sep, '/')
        t = verify.FENCE.sub('', open(p, encoding='utf-8').read())
        m = verify.FM.match(t)
        if not m:
            continue
        rels.append(rel)
        meta[rel] = (yaml.safe_load(m.group(1)) or {}, t[m.end():])
    inb = collections.Counter()
    for rel, (_, body) in meta.items():
        for tgt in LINK.findall(body):
            q = os.path.normpath(os.path.join(os.path.dirname(rel), tgt))
            q = q.replace(os.sep, '/')
            if q in meta and q != rel:
                inb[q] += 1
    rows = []
    for rel in rels:
        fm, _ = meta[rel]
        if fm.get('verified') or rel.endswith('questions.md'):
            continue
        rows.append({
            'kb': kb, 'rel': rel, 'inbound': inb[rel],
            'type': fm.get('type') or '?',
            'title': str(fm.get('title') or rel).strip(),
            'desc': ' '.join(str(fm.get('description') or '').split()),
            'sources': len(fm.get('sources') or []),
        })
    rows.sort(key=lambda r: (-r['inbound'], -r['sources'], r['title'].lower()))
    return rows


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    kbs = args or sorted(d for d in os.listdir(VAULT)
                         if os.path.isdir(os.path.join(VAULT, d, 'Wiki')))
    rows = []
    for kb in kbs:
        rows += bundle(kb)
    blocks = [rows[i:i + SIZE] for i in range(0, len(rows), SIZE)]
    only = None
    if '--block' in sys.argv:
        only = int(sys.argv[sys.argv.index('--block') + 1])

    out = ['# Reading blocks\n',
           '**Generated by `_scripts/readblocks.py`. Do not edit.** '
           'Regenerate it and the blocks renumber around whatever has been '
           'confirmed since.\n',
           '%d concepts still carry no `verified` key, in %d blocks of %d. '
           'Ordered by inbound links within each knowledge base, highest '
           'first.\n' % (len(rows), len(blocks), SIZE),
           'The order is a risk order, not a value order. On 15.08.2026 the '
           'Gamma sitting ran this way and the tail — the concepts nothing '
           'links to — produced more findings than the first three blocks '
           'together, because it held most of that bundle\'s Decision '
           'concepts and a Decision carries its own counterfactual. Do not '
           'stop early on the strength of the ordering.\n']
    for i, b in enumerate(blocks, 1):
        if only and i != only:
            continue
        span = '%s %d..%d' % (b[0]['kb'], b[0]['inbound'], b[-1]['inbound'])
        out.append('## Block %d of %d — %s\n' % (i, len(blocks), span))
        for r in b:
            out.append('**%s** · %s · %s · %d src · %d in'
                       % (r['title'], r['kb'].replace('_kb', ''), r['type'],
                          r['sources'], r['inbound']))
            out.append('%s  \n`%s`\n' % (r['desc'] or '*no description*',
                                         r['rel']))
    text = '\n'.join(out)
    if '--write' in sys.argv:
        d = os.path.join(VAULT, 'Outputs')
        open(os.path.join(d, '_READING-BLOCKS.md'), 'w',
             encoding='utf-8').write(text)
        print('wrote Outputs/_READING-BLOCKS.md — %d concepts, %d blocks'
              % (len(rows), len(blocks)))
    else:
        print(text)


if __name__ == '__main__':
    main()
